//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoonieBear.DeckUnit.Mov4500UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoonieBear.DeckUnit.Mov4500UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string AppBarButton_Save {
            get {
                return ResourceManager.GetString("AppBarButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string AppBarButton_SaveResult {
            get {
                return ResourceManager.GetString("AppBarButton_SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口打开失败 的本地化字符串。
        /// </summary>
        public static string Comm_Failed {
            get {
                return ResourceManager.GetString("Comm_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口服务正常 的本地化字符串。
        /// </summary>
        public static string Comm_OK {
            get {
                return ResourceManager.GetString("Comm_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4500米载人潜器水声通信机-全局设置 的本地化字符串。
        /// </summary>
        public static string GLOBALSETTING_Title_Top {
            get {
                return ResourceManager.GetString("GLOBALSETTING_Title_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水声通信机 的本地化字符串。
        /// </summary>
        public static string Home_Brand {
            get {
                return ResourceManager.GetString("Home_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海洋声学技术实验室 的本地化字符串。
        /// </summary>
        public static string Home_Brand_LOAT {
            get {
                return ResourceManager.GetString("Home_Brand_LOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令行模式 的本地化字符串。
        /// </summary>
        public static string Home_Tile_Console {
            get {
                return ResourceManager.GetString("Home_Tile_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据分析 的本地化字符串。
        /// </summary>
        public static string Home_Tile_Data {
            get {
                return ResourceManager.GetString("Home_Tile_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水声通信 的本地化字符串。
        /// </summary>
        public static string Home_Tile_Live {
            get {
                return ResourceManager.GetString("Home_Tile_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本设置 的本地化字符串。
        /// </summary>
        public static string Home_Tile_Setup {
            get {
                return ResourceManager.GetString("Home_Tile_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4500米载人潜器声学显控程序 的本地化字符串。
        /// </summary>
        public static string Home_Title_ApplicationName {
            get {
                return ResourceManager.GetString("Home_Title_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4500米载人潜器水声通信机-实时通信 的本地化字符串。
        /// </summary>
        public static string Live_Title_Top {
            get {
                return ResourceManager.GetString("Live_Title_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载人潜器声学显控程序 的本地化字符串。
        /// </summary>
        public static string Mov4500_ApplicationName {
            get {
                return ResourceManager.GetString("Mov4500_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载人潜器声学显控程序正在运行 的本地化字符串。
        /// </summary>
        public static string Mov4500_RUNNING {
            get {
                return ResourceManager.GetString("Mov4500_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络未连接 的本地化字符串。
        /// </summary>
        public static string NETWORK_DOWN {
            get {
                return ResourceManager.GetString("NETWORK_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络连接出错！ 的本地化字符串。
        /// </summary>
        public static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络已连接 的本地化字符串。
        /// </summary>
        public static string NETWORK_OK {
            get {
                return ResourceManager.GetString("NETWORK_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信机显控程序 的本地化字符串。
        /// </summary>
        public static string SPLASH_BAND {
            get {
                return ResourceManager.GetString("SPLASH_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与中国科学院声学研究所水声通信机配套使用 的本地化字符串。
        /// </summary>
        public static string SPLASH_BAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("SPLASH_BAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海洋声学技术实验室 的本地化字符串。
        /// </summary>
        public static string SPLASH_COMPANY_NAME {
            get {
                return ResourceManager.GetString("SPLASH_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  © 2016 中国科学院声学研究所  的本地化字符串。
        /// </summary>
        public static string SPLASH_COPY_RIGHT {
            get {
                return ResourceManager.GetString("SPLASH_COPY_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4500米载人潜器声学显控 的本地化字符串。
        /// </summary>
        public static string SPLASH_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("SPLASH_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有 的本地化字符串。
        /// </summary>
        public static string SPLASH_RIGHT_RESERVER {
            get {
                return ResourceManager.GetString("SPLASH_RIGHT_RESERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 2.0 的本地化字符串。
        /// </summary>
        public static string SPLASH_VERSION {
            get {
                return ResourceManager.GetString("SPLASH_VERSION", resourceCulture);
            }
        }
    }
}
